CREATE TABLE IF NOT EXISTS task_item(id INTEGER PRIMARY KEY, title TEXT, color INTEGER)
CREATE TABLE IF NOT EXISTS done_item(id INTEGER PRIMARY KEY, task INTEGER, done_date INTEGER, memo TEXT, registered INTEGER)
